# Form implementation generated from reading ui file 'calculating_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_calculation_dialog(object):
    def setupUi(self, calculation_dialog):
        calculation_dialog.setObjectName("calculation_dialog")
        calculation_dialog.resize(534, 149)
        self.label = QtWidgets.QLabel(parent=calculation_dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 511, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(calculation_dialog)
        QtCore.QMetaObject.connectSlotsByName(calculation_dialog)

    def retranslateUi(self, calculation_dialog):
        _translate = QtCore.QCoreApplication.translate
        calculation_dialog.setWindowTitle(_translate("calculation_dialog", "Heart Disease Predictor by S&N Health - Calculating"))
        self.label.setText(_translate("calculation_dialog", "Calculating your results..."))
