# Form implementation generated from reading ui file 'finished_calculation.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_finished_calculation_dialog(object):
    def setupUi(self, finished_calculation_dialog):
        finished_calculation_dialog.setObjectName("finished_calculation_dialog")
        finished_calculation_dialog.resize(511, 131)
        self.label = QtWidgets.QLabel(parent=finished_calculation_dialog)
        self.label.setGeometry(QtCore.QRect(26, 9, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=finished_calculation_dialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 72, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("nextButton")
        self.retranslateUi(finished_calculation_dialog)
        QtCore.QMetaObject.connectSlotsByName(finished_calculation_dialog)

    def retranslateUi(self, finished_calculation_dialog):
        _translate = QtCore.QCoreApplication.translate
        finished_calculation_dialog.setWindowTitle(_translate("finished_calculation_dialog", "Heart Disease Predictor by S&N Health - Calculation complete!"))
        self.label.setText(_translate("finished_calculation_dialog", "<html><head/><body><p align=\"center\">Calculation complete!</p></body></html>"))
        self.pushButton.setText(_translate("finished_calculation_dialog", "Show my results!"))
