# Form implementation generated from reading ui file 'start_screen_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_start_window(object):
    def setupUi(self, start_window):
        start_window.setObjectName("start_window")
        start_window.resize(650, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(start_window.sizePolicy().hasHeightForWidth())
        start_window.setSizePolicy(sizePolicy)
        start_window.setMinimumSize(QtCore.QSize(650, 200))
        start_window.setMaximumSize(QtCore.QSize(650, 200))
        start_window.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(parent=start_window)
        self.centralwidget.setObjectName("centralwidget")
        self.understand_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.understand_button.setGeometry(QtCore.QRect(250, 470, 321, 61))
        self.understand_button.setObjectName("understand_button")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 601, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.get_started_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.get_started_button.setGeometry(QtCore.QRect(170, 100, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.get_started_button.setFont(font)
        self.get_started_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.get_started_button.setObjectName("nextButton")
        start_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=start_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 21))
        self.menubar.setObjectName("menubar")
        start_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=start_window)
        self.statusbar.setObjectName("statusbar")
        start_window.setStatusBar(self.statusbar)

        self.retranslateUi(start_window)
        QtCore.QMetaObject.connectSlotsByName(start_window)

    def retranslateUi(self, start_window):
        _translate = QtCore.QCoreApplication.translate
        start_window.setWindowTitle(_translate("start_window", "Heart Disease Predictor by S&N Health"))
        self.understand_button.setText(_translate("start_window", "Get Started!"))
        self.label.setText(_translate("start_window", "This tool brought to you by S&N Health will allow you to assess your risk of developing Heart Disease based on your current symptoms and conditions. Press the \"Get Started\" button below to get started!"))
        self.get_started_button.setText(_translate("start_window", "Get Started!"))
